docs/experimental/model_serve.md
mkdocs.yml
waffle_hub/experimental/serve.py

this feature is experimental. see docs/experimental/model_serve.md.

Add Experimental model serving

---

docs/experimental/auto_labeling.md
mkdocs.yml
waffle_hub/experimental/auto_label/README.md
waffle_hub/experimental/auto_label/grounding_dino.py

see docs/experimental/auto_labeling.md

(experimental) add autolabel using GroundingDINO

---

tests/conftest.py
tests/test_dataset.py
tests/test_hub.py
waffle_hub/__init__.py
waffle_hub/dataset/__init__.py
waffle_hub/dataset/adapter/__init__.py
waffle_hub/dataset/adapter/coco.py
waffle_hub/dataset/adapter/yolo.py
waffle_hub/dataset/dataset.py
waffle_hub/experimental/auto_label/grounding_dino.py
waffle_hub/hub/base_hub.py
waffle_hub/hub/model/wrapper.py
waffle_hub/schema/__init__.py
waffle_hub/schema/data.py
waffle_hub/schema/fields/__init__.py
waffle_hub/schema/fields/annotation.py
waffle_hub/schema/fields/base_field.py
waffle_hub/schema/fields/category.py
waffle_hub/schema/fields/image.py
waffle_hub/utils/draw.py

- move Dataset to waffle hub for several reasons...

Add dataset

---

requirements.txt
tests/test_dataset.py
waffle_hub/dataset/dataset.py

Hotfix split dataset

---

waffle_hub/hub/adapter/tx_model/tx_model_hub.py

it is not clear what cause https://github.com/snuailab/waffle_hub/issues/68 
but it fixed

hotfix training failed

---

tests/test_hub.py
waffle_hub/hub/adapter/hugging_face/hugging_face_hub.py
waffle_hub/hub/adapter/hugging_face/train_input_helper.py

add tiny model(YOLOS, ViT) in hugging face format
```
hub = HuggingFaceHub(
name="mnist_det_hugging",
task="object_detection",
model_size="small",
model_type="YOLOS",
root_dir="hubs",
categories=ds.category_names,
)
hub.train(
dataset_path = "datasets/mnist_det/exports/HUGGINGFACE",
epochs=1,
batch_size=8,
workers=4,
device="1",
image_size=512
)
```
```
hub = HuggingFaceHub(
name="mnist_cls_hugging",
task="classification",
model_size="small",
model_type="ViT",
root_dir="hubs",
categories=ds.category_names,
)
hub.train(
dataset_path = "datasets/mnist_cls/exports/HUGGINGFACE",
epochs=10,
batch_size=16,
workers=4,
device="1",
image_size=224
)
```

add small model in hugging face 

---

requirements.txt
tests/test_dataset.py
tests/test_hub.py
waffle_hub/__init__.py
waffle_hub/dataset/dataset.py
waffle_hub/hub/adapter/ultralytics/ultralytics_hub.py
waffle_hub/hub/base_hub.py
waffle_hub/schema/configs.py
waffle_hub/schema/evaluate.py
waffle_hub/schema/result.py
waffle_hub/utils/callback.py
waffle_hub/utils/data.py
waffle_hub/utils/evaluate.py

- add evaluate
- as a baseline, this PR contains `mAP` and `accuracy` only.
- add `Result` schema for easier and intuitive usability.
- change return type `Callback` to `Result`.
- `Result` object has `Callback` object when the `hold` argument is `False`.
- simplify test code
- hotfix dataloader
- #74 should be resolved ASAP.

Add evaluation

---

tests/test_hub.py
waffle_hub/hub/adapter/ultralytics/ultralytics_hub.py
waffle_hub/hub/base_hub.py
waffle_hub/schema/configs.py

- hotfix class mismatch in ultralytics classification
- fp16 export

Hotfix class mismatch and fp16 export

---

waffle_hub/hub/base_hub.py
waffle_hub/utils/callback.py

- train progress will not be reach to 1. before the actual end.
- #58

fix progress

---

waffle_hub/hub/adapter/hugging_face/train_input_helper.py

fix huggingface augmentation

---

waffle_hub/hub/adapter/hugging_face/config.py
waffle_hub/hub/adapter/hugging_face/hugging_face_hub.py
waffle_hub/hub/adapter/tx_model/config.py
waffle_hub/hub/adapter/tx_model/tx_model_hub.py
waffle_hub/hub/adapter/ultralytics/config.py
waffle_hub/hub/adapter/ultralytics/ultralytics_hub.py
waffle_hub/hub/base_hub.py

1. add default_values
```
hub = UltralyticsHub.new(...)
hub.default_values # output: {'epochs': 50, 'image_size': [640, 640], ...}
```
2. add config.py about each model

add default_values

---

waffle_hub/__init__.py
waffle_hub/dataset/adapter/yolo.py
waffle_hub/dataset/dataset.py
waffle_hub/hub/adapter/hugging_face/config.py
waffle_hub/hub/adapter/hugging_face/hugging_face_hub.py
waffle_hub/hub/adapter/hugging_face/train_input_helper.py
waffle_hub/hub/adapter/tx_model/config.py
waffle_hub/hub/adapter/tx_model/tx_model_hub.py
waffle_hub/hub/adapter/ultralytics/config.py
waffle_hub/hub/adapter/ultralytics/ultralytics_hub.py
waffle_hub/hub/base_hub.py
waffle_hub/hub/model/wrapper.py

- huggingface hotfix
- cam baseline

`0.2.1` release

---

waffle_hub/__init__.py
waffle_hub/dataset/dataset.py

1. add split method
2. implement stratified split
3. fix from_yolo bug where id is reset whenever set changes

add Split Method

---

setup.py
tests/test_cli.py
waffle_hub/run.py

implement cli base line
ex) wh hub new ...
hub
- new
- train
- inference
- export
- evaluate
dataset
- new
- split
- from_coco, from_yolo, from_huggingface
- clone
- export

implement cli tool

---

tests/test_cli.py
waffle_hub/dataset/dataset.py
waffle_hub/run.py

if user clone dataset, info.yaml's created time and name is changed

fix info.yaml when clone dataset

---

tests/conftest.py
tests/test_cli.py
tests/test_dataset.py
waffle_hub/dataset/adapter/coco.py
waffle_hub/dataset/adapter/huggingface.py
waffle_hub/dataset/dataset.py
waffle_hub/schema/fields/annotation.py
waffle_hub/utils/conversion.py

Hotfix 0525

---

requirements.txt
tests/test_dataset.py
waffle_hub/schema/fields/annotation.py

add auto_area

---

tests/test_dataset.py
waffle_hub/dataset/dataset.py

download sample
usage:
```
ds = Dataset.sample(
name="sample",
root_dir="datasets",
task=TaskType.CLASSIFICATION,
)
```

download sample

---

waffle_hub/dataset/dataset.py

fix categort_id when import dataset in ocr

fix categort_id when import dataset in ocr 

---

tests/test_cli.py
tests/test_ddp.py
tests/test_hub.py
waffle_hub/__init__.py
waffle_hub/dataset/dataset.py
waffle_hub/hub/adapter/autocare_dlt/autocare_dlt_hub.py
waffle_hub/hub/adapter/autocare_dlt/config.py
waffle_hub/hub/adapter/transformers/config.py
waffle_hub/hub/adapter/transformers/train_input_helper.py
waffle_hub/hub/adapter/transformers/transformers_hub.py
waffle_hub/hub/adapter/ultralytics/config.py
waffle_hub/hub/hub.py
waffle_hub/hub/model/wrapper.py

before
```
hub = Hub.new(...)
hub.train(dataset_path = ....)
```
after
```
ds = Dataset.load(...)
hub = Hub.new(...)
hub.train(ds, ...)
```

run eval after train 

---

waffle_hub/utils/data.py

hotfix for get_feature_map's same result

hotfix for get_feature_map's same result

---

waffle_hub/experimental/auto_label/README.md
waffle_hub/experimental/auto_label/grounding_dino.py

[Update] Auto labeling

---

.github/workflows/ci.yaml
.gitignore
waffle_hub/hub/adapter/transformers/transformers_hub.py
waffle_hub/hub/hub.py
waffle_hub/utils/metric_logger.py

- weakly integrated `tensorboard` and `mlflow` .
- It will only log training metrics
- tensorboard save path : path/to/hub/logs
- mlflow save path : working directory or env path
- Both modules are not necessary. It will be automatically detected if it has been installed.
- `pip install tensorboard mlflow`

Add metric logger

---

tests/test_dataset.py
waffle_hub/dataset/dataset.py

Usage
```
ds.draw_annotations()
print(ds.draw_dir.exists())
```
to-be
1. add draw_dir cached_property
2. add draw_annotations(image_ids=[] or None) func

add draw_annotations func

---

tests/conftest.py
tests/test_cli.py
tests/test_hub.py
waffle_hub/hub/hub.py
waffle_hub/schema/configs.py
waffle_hub/schema/data.py
waffle_hub/utils/data.py

Add video inference

---

tests/test_dataset.py
waffle_hub/__init__.py
waffle_hub/dataset/dataset.py

`0.2.8` release

---

waffle_hub/dataset/adapter/yolo.py
waffle_hub/dataset/cli.py
waffle_hub/dataset/dataset.py
waffle_hub/hub/cli.py

- from_yolo bug fix
- create_index bug fix

Hotfix from yolo

---

tests/test_hub.py
waffle_hub/hub/adapter/ultralytics/ultralytics_hub.py

- overwrite our parameters with advance params
- force letter_box to be true in ultralytics

hotfix ultralytics

---

requirements.txt
tests/test_dataset.py
waffle_hub/__init__.py
waffle_hub/dataset/adapter/__init__.py
waffle_hub/dataset/adapter/label_studio.py
waffle_hub/dataset/dataset.py
waffle_hub/utils/metric_logger.py

Label studio

---

tests/test_cli.py
waffle_hub/__init__.py
waffle_hub/hub/adapter/autocare_dlt/autocare_dlt_hub.py
waffle_hub/hub/adapter/transformers/transformers_hub.py
waffle_hub/hub/adapter/ultralytics/ultralytics_hub.py
waffle_hub/hub/hub.py

Modify to work on Windows
- fix backend.lower to upper
- add __ne__ func
- **modify "YOLO" to "ULTRALYTICS"** 
- Add some additional changes for the Windows environment

Modify to work on Windows

---

.github/workflows/ci.yaml
requirements.txt
tests/test_utils.py
waffle_hub/__init__.py
waffle_hub/hub/adapter/autocare_dlt/autocare_dlt_hub.py
waffle_hub/hub/hub.py
waffle_hub/schema/evaluate.py
waffle_hub/utils/evaluate.py

Update Evaluation Metrics for classification and Detection

Update, Evaluation Metrics (cls & det)

---

requirements.txt
waffle_hub/dataset/adapter/label_studio.py
waffle_hub/dataset/adapter/yolo.py
waffle_hub/dataset/dataset.py
waffle_hub/experimental/auto_label/grounding_dino.py
waffle_hub/hub/hub.py
waffle_hub/utils/data.py
waffle_hub/utils/draw.py

- Use "waffle_utils" to load or save images
- Fix bugs that occur when using hierarchical directory structures
- `inference`
- Fix bugs that are saved by changing RGB when used as  video type
solves: #272, #271

HotFix: `Inference` & hierarchical directory structure

---

.github/workflows/ci.yaml
tests/test_cli.py
tests/test_dataset.py
tests/test_hub.py
waffle_hub/__init__.py
waffle_hub/hub/hub.py
waffle_hub/schema/fields/image.py

- add `hold` argument for `export_waffle` function
- update test code

`0.2.14` release

---

requirements.txt
waffle_hub/__init__.py

- fix `waffle_utils` version to `0.3.3`

`0.2.15` release 

---

waffle_hub/dataset/adapter/yolo.py

Feat. Add resize image to learn yolo classification

Feat. Export YOLO Classification w/ Resize image

---

requirements.txt
tests/conftest.py
tests/test_dataset.py
tests/test_hub.py
tests/test_utils.py
waffle_hub/__init__.py
waffle_hub/dataset/adapter/autocare_dlt.py
waffle_hub/dataset/dataset.py
waffle_hub/hub/adapter/autocare_dlt/autocare_dlt_hub.py
waffle_hub/hub/adapter/autocare_dlt/config.py
waffle_hub/hub/adapter/autocare_dlt/configs/model_cfg.py
waffle_hub/hub/hub.py
waffle_hub/hub/model/wrapper.py
waffle_hub/schema/evaluate.py
waffle_hub/schema/fields/annotation.py
waffle_hub/utils/conversion.py
waffle_hub/utils/draw.py
waffle_hub/utils/evaluate.py

1. Semantic Segmentation Porting in DLT
- metric: mpa (mean pixel accuracy), iou
2. After the training is completed, "artifacts/model.json" will be copied to "configs/model.json" << Please provide feedback on this.
- run dlt test code

Semantic Segmentation Porting

---

requirements.txt
waffle_hub/__init__.py
waffle_hub/utils/data.py

hotfix release for 23.11.13 tx release

hotfix resize image

---

waffle_hub/dataset/adapter/autocare_dlt.py
waffle_hub/dataset/adapter/coco.py
waffle_hub/dataset/adapter/transformers.py
waffle_hub/dataset/adapter/yolo.py
waffle_hub/dataset/dataset.py

- Add
- `add_background_images`
- args : `background_image_dir` (Union[str, Path]): background image directory.
- create image_info and copy raw iamges to `raw/background_dir` 
- create set `background.json`
- `get_background_ids`
- return background set ids
- export with background
others.. (WIP)
It was confirmed that the background was included when training `Yolo`.
However, it is necessary to verify that the background is normally included in other tasks using the Coco format.

Add background in Dataset 
